# Setting up the Ontrack CLI
.ontrack_setup:
   before_script: |

      # if [[ "${ONTRACK_URL}" == "" ]]
      # then
      #   echo "Missing ONTRACK_URL variable."
      #   exit 1
      # fi

      # if [[ "${ONTRACK_TOKEN}" == "" ]]
      # then
      #   echo "Missing ONTRACK_TOKEN variable."
      #   exit 1
      # fi

      if [[ "${ONTRACK_CLI_VERSION}" == "" ]]
      then
        echo "No ONTRACK_CLI_VERSION defined at project or group level, using 0.1.18 by default."
        export ONTRACK_CLI_VERSION=0.1.21
      fi

      export OS=$(uname -s | tr '[:upper:]' '[:lower:]')

      export ARCH=$(uname -m)
      if [[ "${ARCH}" == "x86_64" ]]
      then
        export ARCH="386"
      fi

      export ONTRACK_CLI_URL="https://github.com/nemerosa/ontrack-cli/releases/download/${ONTRACK_CLI_VERSION}/ontrack-cli-${OS}-${ARCH}"
      echo "Downloading the Ontrack CLI from ${ONTRACK_CLI_URL}"
      curl --output ontrack-cli --fail -L "${ONTRACK_CLI_URL}"

      chmod u+x ontrack-cli
      ./ontrack-cli version --cli

      echo "Setting up Ontrack config to ${ONTRACK_URL}"
      ontrack-cli config create default "${ONTRACK_URL}" --token "${ONTRACK_TOKEN}""
